"""add camera ip columns to baby_profiles

Revision ID: 1a306607c5fa
Revises: a8e8d9985787
Create Date: 2025-05-23 15:58:57.186734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a306607c5fa'
down_revision: Union[str, None] = 'a8e8d9985787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby_profiles', sa.Column('head_camera_ip', sa.String(length=100), nullable=True))
    op.add_column('baby_profiles', sa.Column('static_camera_ip', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baby_profiles', 'static_camera_ip')
    op.drop_column('baby_profiles', 'head_camera_ip')
    # ### end Alembic commands ###
