"""added 'already_logged_in' Column in 'users' table.

Revision ID: acbaa41dcae6
Revises: add_camera_connection_state
Create Date: 2025-06-25 20:22:26.432226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acbaa41dcae6'
down_revision: Union[str, None] = 'add_camera_connection_state'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_column('baby_profiles', 'head_camera_on')
    op.drop_column('baby_profiles', 'static_camera_on')

    # Step 1: Add with default to avoid null violation
    op.add_column('users', sa.Column(
        'already_logged_in',
        sa.Boolean(),
        nullable=False,
        server_default=sa.text('false')
    ))

    # Step 2: Remove the default if you don't want it in the DB schema
    op.alter_column('users', 'already_logged_in', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'already_logged_in')
    op.add_column('baby_profiles', sa.Column(
        'static_camera_on',
        sa.BOOLEAN(),
        server_default=sa.text('false'),
        autoincrement=False,
        nullable=False
    ))
    op.add_column('baby_profiles', sa.Column(
        'head_camera_on',
        sa.BOOLEAN(),
        server_default=sa.text('false'),
        autoincrement=False,
        nullable=False
    ))
    # ### end Alembic commands ###