"""added 'head_camera_model_last_updated_time' and 'static_camera_model_last_updated_time' columns to baby_profiles table

Revision ID: c1e86434bdd4
Revises: c21773ef1d78
Create Date: 2025-06-23 13:09:01.430435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1e86434bdd4'
down_revision: Union[str, None] = 'c21773ef1d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_files_id', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_cameras_id', table_name='cameras')
    op.drop_table('cameras')
    op.add_column('baby_profiles', sa.Column('head_camera_model_last_updated_time', sa.DateTime(), nullable=True))
    op.add_column('baby_profiles', sa.Column('static_camera_model_last_updated_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baby_profiles', 'static_camera_model_last_updated_time')
    op.drop_column('baby_profiles', 'head_camera_model_last_updated_time')
    op.create_table('cameras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['baby_profiles.id'], name='cameras_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cameras_pkey')
    )
    op.create_index('ix_cameras_id', 'cameras', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='files_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='files_pkey')
    )
    op.create_index('ix_files_id', 'files', ['id'], unique=False)
    # ### end Alembic commands ###
