"""Add user_fcm_tokens table

Revision ID: ca2c2006013c
Revises: d2c3589a42aa
Create Date: 2025-06-06 15:23:24.058455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2c2006013c'
down_revision: Union[str, None] = 'd2c3589a42aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
