"""updated users and baby_profiles tables for CRUD code

Revision ID: d2c3589a42aa
Revises: d469acaf91a5
Create Date: 2025-06-04 17:44:01.633037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c3589a42aa'
down_revision: Union[str, None] = 'd469acaf91a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby_profiles', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('baby_profiles', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('baby_profiles', sa.Column('head_camera_model_classes', sa.JSON(), nullable=True))
    op.add_column('baby_profiles', sa.Column('static_camera_model_classes', sa.JSON(), nullable=True))
    op.drop_column('baby_profiles', 'sensitivity')
    op.drop_column('baby_profiles', 'dangerous_objects_AI')
    op.drop_column('baby_profiles', 'dangerous_objects_static')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby_profiles', sa.Column('dangerous_objects_static', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('baby_profiles', sa.Column('dangerous_objects_AI', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('baby_profiles', sa.Column('sensitivity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('baby_profiles', 'static_camera_model_classes')
    op.drop_column('baby_profiles', 'head_camera_model_classes')
    op.drop_column('baby_profiles', 'weight')
    op.drop_column('baby_profiles', 'gender')
    # ### end Alembic commands ###
