"""Add detection system flags to baby_profiles (clean)

Revision ID: f35c72c5fd61
Revises: 2e73c15ae206
Create Date: 2025-06-26 20:05:56.095592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35c72c5fd61'
down_revision: Union[str, None] = '2e73c15ae206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('baby_profiles', sa.Column(
        'head_camera_in_detection_system_on', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('baby_profiles', sa.Column(
        'static_camera_in_detection_system_on', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('baby_profiles', 'static_camera_in_detection_system_on')
    op.drop_column('baby_profiles', 'head_camera_in_detection_system_on')
    # ### end Alembic commands ###
